version: '3'

services:
  mysql:
    image: "mysql:5.7.24"
    container_name: "vehicle-mysql"
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - databases_mysql:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/databases-backup.sql
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: admin
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: vehicle
  vehicle-api:
    build:  
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      PORT: 5000
    depends_on: 
      - mysql
  back-office-web:
    build:  
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
    environment:
      PORT: 3000
    restart: always
    depends_on: 
      - vehicle-api
volumes:
  databases_mysql: