version: '3'

services:
  mysql:
    image: "mysql:5.7.24"
    container_name: "vehicle-mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: admin
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: nest
  api-nest:
    container_name: vehicle-api
    build:  
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./:/app
    environment:
      PORT: 5000
    depends_on: 
      - mysql
    
