CREATE DATABASE IF NOT EXISTS dev; 
CREATE DATABASE IF NOT EXISTS test;
CREATE USER 'admin'@'localhost' IDENTIFIED BY 'P@ssw0rd';
GRANT ALL PRIVILEGES ON * . * TO 'admin'@'localhost';
FLUSH PRIVILEGES;